#! /usr/bin/env bash

tee "$HOME"/.local/share/applications/htop.desktop > /dev/null <<EOF
NoDisplay=true
EOF

tee "$HOME"/.local/share/applications/syncthing-start.desktop > /dev/null <<EOF
NoDisplay=true
EOF
