#! /usr/bin/env bash

# shellcheck disable=SC2034

packages=(
  'htop'
  'snapper'
  'vim'
  'syncthing'
#  'dnf-automatic'
  'nautilus'
#  'gnome-console'
  'virt-manager'
  'borgmatic'
  'android-tools'
  'kernel-tools'
  )

removals=(
  'gnome-boxes'
  'gnome-clocks'
  'gnome-characters'
  'gnome-contacts'
  'gnome-connections'
  'gnome-font-viewer'
  'gnome-software'
  'gnome-logs'
  'gnome-calendar'
  'gnome-maps'
  'gnome-tour'
  'yelp'
  'gnome-weather'
  'gnome-text-editor'
  'totem*'
  'libreoffice*'
  'rhythmbox'
  'cheese'
  'simple-scan'
  'evince*'
  'loupe'
  'gnome-calculator'
  'baobab'
  'mediawriter'
  'firefox'
  'firefox-langpacks'
#  'gnome-terminal'
)

system_flatpaks=(
  'org.gnome.baobab'
  'org.gnome.TextEditor'
  'org.gnome.Evince'
  'org.gnome.Calendar'
  'org.gnome.Contacts'
  'org.gnome.Logs'
  'org.gnome.Loupe'
  'org.gnome.Snapshot'
  'org.gnome.Calculator'
  'org.mozilla.firefox'
  'org.freedesktop.Platform.ffmpeg-full/x86_64/23.08'
  'org.gnome.Firmware'
  'com.github.tchx84.Flatseal'
#  'org.gnome.Geary'
  'org.gnome.World.PikaBackup'
)

user_flatpaks=(
#  'com.spotify.Client'
  'com.yubico.yubioath'
  'org.gimp.GIMP'
  'org.signal.Signal'
  'org.chromium.Chromium'
  'com.bitwarden.desktop'
  'com.visualstudio.code-oss'
)