#! /usr/bin/env bash

# shellcheck disable=SC2154,SC1091

### config options ###
source ../vars/os/minimal


### tests ###
if [[ ! "$EUID" = "0" ]]; then
    echo "Please run as root, exiting..."
    sleep 2
    exit
fi

if ! mount | grep -oq '/home type btrfs'; then
    echo "/home is not a btrfs subvolume, exiting..."
    sleep 2
    exit
fi


### dnf ###
dnf autoremove --assumeyes "${removals[@]}"
dnf update --assumeyes
dnf install --assumeyes "${packages[@]}"

tee /etc/systemd/system/dnf-offline-automatic.service > /dev/null <<EOF
[Unit]
Description=Start automatic offline updates on reboot
Wants=network-online.target
After=network-online.target
StartLimitIntervalSec=10m
StartLimitBurst=5

[Service]
Type=oneshot
Restart=on-failure
RestartSec=60s

# refresh repo
ExecStartPre=/usr/bin/pkcon refresh force

# download updates
ExecStart=-/usr/bin/pkcon update --only-download

# prepare update
ExecStart=-/usr/bin/pkcon offline-get-prepared

# set magiclink
ExecStartPost=-/usr/bin/pkcon offline-trigger
EOF

tee /etc/systemd/system/dnf-offline-automatic.timer > /dev/null <<EOF
[Unit]
Description=Timer for automatic offline updates on reboot
Wants=network-online.target
After=network-online.target

[Timer]
OnBootSec=1h
OnUnitInactiveSec=1d
OnCalendar=daily
Persistent=true

[Install]
WantedBy=timers.target
EOF

systemctl enable dnf-offline-automatic.timer


### bash ###
tee /etc/profile.d/prompt.sh > /dev/null <<EOF
#! /usr/bin/env bash

export PS1="[\[\e[31m\]\u\[\e[m\]@\h] \[\e[01;31m\]:\[\e[m\]\[\e[01;31m\]:\[\e[m\] \W \[\e[01;31m\]>\[\e[m\] "
EOF


### snapper ###
home_mnt="$(lsblk --output MOUNTPOINTS | grep 'home$')"

if [ ! -d "$home_mnt"/.snapshots ]; then
  btrfs subvolume create "$home_mnt"/.snapshots
fi

mkdir --parents /etc/systemd/system/snapper-{cleanup.timer.d,timeline.timer.d}
mkdir --parents /etc/snapper/configs

tee /etc/systemd/system/snapper-cleanup.timer.d/override.conf > /dev/null <<EOF
[Timer]
OnBootSec=
OnUnitActiveSec=
OnCalendar=hourly
Persistent=true
EOF

tee /etc/systemd/system/snapper-timeline.timer.d/override.conf > /dev/null <<EOF
[Timer]
Persistent=true
EOF

tee /etc/snapper/configs/home > /dev/null <<EOF
# subvolume to snapshot
SUBVOLUME="$home_mnt"

# filesystem type
FSTYPE="btrfs"

# create hourly snapshots
TIMELINE_CREATE="yes"

# cleanup hourly snapshots after some time
TIMELINE_CLEANUP="yes"

# limits for timeline cleanup
TIMELINE_MIN_AGE="1800"
TIMELINE_LIMIT_HOURLY="24"
TIMELINE_LIMIT_DAILY="3"
TIMELINE_LIMIT_WEEKLY="0"
TIMELINE_LIMIT_MONTHLY="0"
TIMELINE_LIMIT_YEARLY="0"

# cleanup empty pre-post-pairs
EMPTY_PRE_POST_CLEANUP="yes"
EOF

sed --in-place "s@^SNAPPER_CONFIGS=.*@SNAPPER_CONFIGS=\"home\"@" /etc/sysconfig/snapper

systemctl enable snapper-timeline.timer snapper-cleanup.timer


### vim ###
# configure vim
tee /etc/vimrc > /dev/null <<EOF
set autoindent
set autoread
set autowrite
set expandtab
set hidden
set ignorecase
set incsearch
set laststatus=2
set linebreak
set list listchars=tab:▸\ ,trail:·
set nofoldenable
set nojoinspaces
set number
set path+=**
set printoptions=paper:A4,syntax:n,number:y
set shiftwidth=4
set showbreak=↪\
set splitbelow
set splitright
set statusline=\(%n\)\ %<%.99f\ %y\ %w%m%r%=%-14.(%l,%c%V%)\ %P
set tabstop=4
set textwidth=120
set wrapscan
EOF
