#! /usr/bin/env bash

tee "$HOME"/.config/systemd/user/flatpak-automatic.service > /dev/null <<EOF
[Unit]
Description=Service for flatpak-automatic
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
Restart=on-failure
RestartSec=60s

# uninstall unused flatpaks
ExecStart=/usr/bin/dbus-run-session /usr/bin/flatpak --user uninstall --unused --assumeyes --noninteractive --delete-data

# update
ExecStart=/usr/bin/dbus-run-session /usr/bin/flatpak --user update --assumeyes --noninteractive

# repair
ExecStart=/usr/bin/dbus-run-session /usr/bin/flatpak --user repair
EOF

tee "$HOME"/.config/systemd/user/flatpak-automatic.timer > /dev/null <<EOF
[Unit]
Description=Trigger for flatpak-automatic.service

[Timer]
OnBootSec=1h
OnUnitInactiveSec=1d
OnCalendar=daily
Persistent=true

[Install]
WantedBy=timers.target
EOF